[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Function"
Version = "0.1.0"
Type = "Executable"
Description = "Declaring functions with parameters and a result, and calling them"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Io = { Namespace = "Rux", Version = "*" }
