[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Comment"
Version = "0.1.0"
Type = "Executable"
Description = "Line, block, nested and documentation comments"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Io = { Namespace = "Rux", Version = "*" }
