[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Guard"
Version = "0.1.0"
Type = "Executable"
Description = "Guards: adding an if condition to a match arm"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Io = { Namespace = "Rux", Version = "*" }
