[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "SharedLibrary"
Version = "0.1.0"
Type = "SharedLibrary"
Description = "A library loaded at run time, and the functions it exports"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
