[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Indexer"
Version = "0.1.0"
Type = "Executable"
Description = "Indexing a type of your own with func [] and func []="
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Io = { Namespace = "Rux", Version = "*" }
